version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app:create_app('production')
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      PASSWORD_SALT: ${PASSWORD_SALT}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: 587
      MAIL_USE_TLS: 'true'
      MAIL_USE_SSL: 'false'
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      CLIENT_SECRETS_FILE: ${CLIENT_SECRETS_FILE}
      REDIRECT_URI: ${REDIRECT_URI}
      FLASKY_ADMIN: ${FLASKY_ADMIN}
      MAIL_SENDER: ${MAIL_SENDER}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_blog
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
